server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurants/**
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/api/v1/**
    
    bus:
      enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

info:
  app:
    name: api-gateway-service
    description: this is api-gateway-service for gateway related details
    version: 1.0v
