# Eureka Client Configuration (Sab services use karengi)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

# Actuator Settings (Sabke liye common)
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

# RabbitMQ Connection (Jin services ko need hogi)
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # Spring Cloud Bus (For dynamic updates)
  cloud:
    bus:
      enabled: true